# fly.toml app configuration file generated for accessibilityquestions on 2026-03-03T19:20:16Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'accessibilityquestions'
primary_region = 'ams'

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[checks]
  [checks.httpcheck]
    type = "http"
    port = 3000
    method = "GET"
    path = "/"
    interval = "10s"
    timeout = "5s"
    grace_period = "10s"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
