app = 'accessibilityquestions'
primary_region = 'ams'

[build]
  dockerfile = "Dockerfile"

[env]
  DATA_DIR = '/data'
  ADMIN_KEY = 'necypaa2026'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

[checks]
  [checks.httpcheck]
    type = "http"
    port = 3000
    method = "GET"
    path = "/"
    interval = "10s"
    timeout = "5s"
    grace_period = "10s"

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
